### PR TITLE
Add Cody of ajhous44 and Mentat AI

### PR DESCRIPTION
**Pull request by abdshomad**
1. Cody of ajhous44 - https://github.com/ajhous44/cody

An AI assistant designed to let you interactively query your codebase using natural language. By utilizing vector embeddings, chunking, and OpenAI's language models, Cody can help you navigate through your code in an efficient and intuitive manner.

2. Mentat - https://github.com/biobootloader/mentat
Mentat is the AI tool that assists you with any coding task, right from your command line.
Unlike Copilot, Mentat coordinates edits across multiple locations and files. And unlike ChatGPT, Mentat already has the context of your project - no copy and pasting required!

### CODE REVIEW

**Comment by mlejva** [comment]
Hey @abdshomad, I'd think about changing the name of your Cody to something else as there's already very popular coding agent called [Cody from SourceGraph](https://about.sourcegraph.com/cody)

**Comment by abdshomad** [comment]
> 

Hi, the 2nd Cody is not mine. I just found the same name but different author. So that's why I named if Cody of "the author name". 

What could be the best approach to differentiate it?

**Comment by abdshomad** [comment]
OK. Then, I will update it.

**Comment by tizkovatereza** [comment]
Hey abdshomad, thanks a lot for the update. 
Also, you have won the competition for adding the most agents, so if you want cookies delivered, feel free to reach out via our discord https://discord.gg/35NF4Y8WSE or my twitter https://twitter.com/tereza_tizkova.

🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪

**Pull request merged**
